In [19]:
import numpy as np
import pandas as pd

1. Row-wise & Column-wise Sum

In [3]:
arr=np.array([[1,2,3],[4,5,6]])
print("Row Sum :", np.sum(arr,axis=1) )
print("Column Sum :", np.sum(arr,axis=0) )

Row Sum : [ 6 15]
Column Sum : [5 7 9]

2. Find Max Element and Its Index

In [ ]:
arr=np.array([10,50,20,80,30])


print("Max : ", np.max(arr))
print("Index of Max : ", np.argmax(arr))

Max :  80
Index of Max :  3

3. Matrix Multiplication

In [15]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
# c=np.array([[15,6],[7,8]])

print("Matrix Multiplication:", np.dot(a,b))

Matrix Multiplication: [[19 22]
 [43 50]]

4. Replace Elements Based on Condition

In [17]:
arr=np.array([1,7,3,4,5,6])

arr[arr>3]=0
print(arr)

[1 0 3 0 0 0]

Pandas

1. Student Data Analysis

In [20]:
df=pd.DataFrame({
    "Name":["A","B","C","D"],
    "Marks":[90,75,60,85]
})

print("Average :",df["Marks"].mean())
print("Max Marks :",df["Marks"].max())

print("Students > 80: \n", df[df["Marks"]>80])

Average : 77.5
Max Marks : 90
Students > 80:
   Name  Marks
0    A     90
3    D     85

Adding Grade column

In [23]:
df["Grade"]=["A" if m>80 else "B" for m in df["Marks"]]

In [22]:
df

  Name  Marks Grade
0    A     90     A
1    B     75     B
2    C     60     B
3    D     85     A

Renaming the column  Marks to Score and deleting the  Grade column drop

In [24]:
df.drop("Grade",axis=1,inplace=True)

df.rename(columns={"Marks":"Score"}, inplace=True)

df

  Name  Score
0    A     90
1    B     75
2    C     60
3    D     85