## Numpy /Pandas

Reshape an array

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6])

print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]

In [4]:
arr=np.array([1,2,3,4,5,6])

print(arr.reshape(3,2))

[[1 2]
 [3 4]
 [5 6]]

In [5]:
arr=np.array([1,2,3,4,5,6])

print(arr.reshape(6,1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]

In [6]:
arr=np.array([1,2,3,4,5,6])

print(arr.reshape(1,6))

[[1 2 3 4 5 6]]

In [7]:
arr=np.array([1,2,3,4,5,6])

print(arr.reshape(4,1))

ValueError: cannot reshape array of size 6 into shape (4,1)

Important Functions

In [8]:
arr=np.array([1,2,3,4,5,6])

In [9]:
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(np.amax(arr))

21
3.5
1.707825127659933
6

In [12]:
print(np.random.rand(3))
print(np.random.randint(1,10,5))

[0.16366388 0.80993467 0.73212314]
[6 5 8 6 7]

Attributes

In [13]:
arr=np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr.ndim)
print(arr.size)

(2, 3)
2
6

Pandas Basics

In [14]:
import pandas as pd

In [18]:
s=pd.Series([10,20,30,40,50,60])
print(s)

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [19]:
print(s.head())
print(s.tail())
print(s+5)

0    10
1    20
2    30
3    40
4    50
dtype: int64
1    20
2    30
3    40
4    50
5    60
dtype: int64
0    15
1    25
2    35
3    45
4    55
5    65
dtype: int64

Data Frame Creation

In [20]:
df=pd.DataFrame({
    "Name": ["A","B"],
    "Marks" : [90,80]
})

print(df)

  Name  Marks
0    A     90
1    B     80

Column Operations

In [21]:
print(df["Marks"])

0    90
1    80
Name: Marks, dtype: int64

In [23]:
df["Age"]=[20,22]
df

  Name  Marks  Age
0    A     90   20
1    B     80   22

In [24]:
df.drop("Age",axis=1, inplace=True)
df

  Name  Marks
0    A     90
1    B     80

Filtering

In [26]:
print(df[df["Marks"]>85])

  Name  Marks
0    A     90

Missing Data

In [28]:
df["Marks"][0]=None
print(df.isnull())
print(df.fillna(0))
df

    Name  Marks
0  False  False
1  False  False
  Name  Marks
0    A     90
1    B     80

C:\Users\TUF A15\AppData\Local\Temp\ipykernel_17712\338736855.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  df["Marks"][0]=None

  Name  Marks
0    A     90
1    B     80

Aggregation

In [29]:
df.to_csv("data.csv")
new_df=pd.read_csv("data.csv")
print(new_df)

   Unnamed: 0 Name  Marks
0           0    A     90
1           1    B     80

---